spring:
  application:
    name: document-manager
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:docmgr}
    username: ${POSTGRES_USER:docmgr_user}
    password: ${POSTGRES_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  
  servlet:
    multipart:
      max-file-size: ${UPLOAD_MAX_SIZE:50MB}
      max-request-size: ${UPLOAD_MAX_SIZE:50MB}
      enabled: true
      file-size-threshold: 2MB

server:
  port: ${SERVER_PORT:3000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.docmgr: ${LOG_LEVEL:INFO}
    org.springframework.web: ${LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  upload:
    directory: ${UPLOAD_DIR:/tmp/uploads}
    temp-directory: ${TEMP_DIR:/tmp}
  
  llm:
    gemini:
      api-key: ${GEMINI_API_KEY:}
      base-url: https://generativelanguage.googleapis.com
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      default-model: ${OLLAMA_DEFAULT_MODEL:llama3.1}
  
  security:
    jwt:
      secret: ${JWT_SECRET:}
    cors:
      allowed-origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}
      allowed-methods: ${CORS_METHODS:GET,POST,PUT,DELETE,OPTIONS}
      allowed-headers: ${CORS_HEADERS:*}
      allow-credentials: true